version: '3.1'
networks:
  laravel:

services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: mailhog
        ports:
            - '38001:8025'
        networks:
          - laravel

    redis:
        image: 'redis:alpine'
        container_name: redis
        networks:
          - laravel

    postgres:
        image: 'postgres:11.1-alpine'
        container_name: postgres
        volumes:
            - './src:/var/www/html'
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=db_password
            - POSTGRES_DB=sampledb
        ports:
            - '38004:5432'
        networks:
          - laravel
          
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        ports:
          - "5050:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: pgadmin@email.account
          PGADMIN_DEFAULT_PASSWORD: pgadmin_password
        volumes:
          - ./pgadmin-data:/var/lib/pgadmin
        depends_on: 
          - postgres
        links:
          - postgres
        networks:
          - laravel

    webserver:
        image: 'nginx:alpine'
        container_name: nginx
        volumes:
            - './src:/var/www/html'
            - './dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '38000:80'
        depends_on:
          - php
          - redis
          - postgres
          - mailhog
        networks:
          - laravel

    php:
        container_name: php
        build: dockerfiles/php-fpm
        volumes:
            - './src:/var/www/html'
            - './dockerfiles/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        networks:
          - laravel
